#!/bin/bash

# 1. 首先需要安装一个全局 Node 第三方包，用于文件夹监视
#      npm i -g chokidar-cli --registry=http://registry.npm.taobao.org
# 2. 设置一个环境变量 DEV_IP，提供给下面的命令使用
#    这个变量是远程到服务器的 SSH 端口号，根据使用的 Shell 不同，执行命令
#    bash:
#      echo 'export DEV_IP=168' >> ~/.bashrc
#    zsh:
#      echo 'export DEV_IP=168' >> ~/.zshrc
# 3. 关闭终端窗口再打开就可以正常运行了
#
# 注意：如果提示 ./sync 不能运行需要添加权限
#   chmod +x ./sync

syncfile() {
  # echo 'syncfile-$1' $1

  rsync -azqh \
    --delete \
    --progress \
    --exclude=node_modules/ \
    --exclude=.git/ \
    --exclude=yarn.lock \
    --exclude=sync \
    --exclude=.DS_Store \
    `pwd`/ root@192.168.1.$DEV_IP:/root/workspace/test/test-networkService/
}

filename=$1
if [ -z "$filename" ]
then
  syncfile ''
  echo -e "transfer \033[0;32msuccess\033[0m: \033[0;33mall\033[0m" "\033[0;35m$(date "+%H:%M:%S")\033[0m"
  chokidar "**/*" --silent -c "$0 {path}"
else
  syncfile $filename
  echo -e "transfer \033[0;32msuccess\033[0m:" "\033[0;33m$filename\033[0m" "\033[0;35m$(date "+%H:%M:%S")\033[0m"
fi
